# Generated by Django 5.0.2 on 2024-02-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_notes_for_note', to='backend.sharednoteuser'),
        ),
        migrations.AlterField(
            model_name='sharednoteuser',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_users_for_note', to='backend.note'),
        ),
    ]
